### ISSUE TITLE
Building 1.9.0 with externally installed SeqAn: 'expected nested-name-specifier before ‘SimdVector’'

### ISSUE THREAD

**Issue by satta** [seqan/lambda#64]
Hi,

while preparing a Debian package for Lambda 1.9.0, I am trying to build it with an external copy of SeqAn 2.2.0 (include files in `/usr/include/seqan`, `FindSeqan.cmake` and friends in `/usr/share/seqan/cmake` appended to `CMAKE_MODULE_PATH`.

Shortly after starting the build with GCC 6.1.1 (details below), the build stops with an error. See the log below up to the first error, full log attached is here: 
[lambda_build.log.txt](https://github.com/seqan/lambda/files/427246/lambda_build.log.txt)

```
	cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=None -DCMAKE_INSTALL_SYSCONFDIR=/etc -DCMAKE_INSTALL_LOCALSTATEDIR=/var -DLAMBDA_NATIVE_BUILD=OFF -DLAMBDA_MMAPPED_DB=ON
[1mCompiler Detection[m
-- The CXX compiler identification is GNU 6.1.1
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done

[1mDependency detection[m
-- Performing Test CXX14_BUILTIN
-- Performing Test CXX14_BUILTIN - Success
-- Looking for C++ include execinfo.h
-- Looking for C++ include execinfo.h - found
--   Determined version is 2.2.0
-- These dependencies where found:
     OPENMP     TRUE      -fopenmp
     ZLIB       TRUE      1.2.8
     BZIP2      TRUE      1.0.6
     SEQAN      TRUE      2.2.0
-- The requirements where met.

[1mBuild configuration[m
-- LAMBDA version is: 1.9.0
-- The following options are selected for the build:
     LAMBDA_FASTBUILD         OFF
     LAMBDA_LINGAPS_OPT       OFF
     LAMBDA_MMAPPED_DB        ON
     LAMBDA_NATIVE_BUILD      OFF
     LAMBDA_STATIC_BUILD      OFF
-- Run 'cmake -LH' to get a comment on each option.
-- Remove CMakeCache.txt and re-run cmake with -DOPTIONNAME=ON|OFF to change an option.
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_INSTALL_LOCALSTATEDIR
    CMAKE_INSTALL_SYSCONFDIR


-- Build files have been written to: /vagrant/lambda-align/obj-x86_64-linux-gnu
make[1]: Leaving directory '/vagrant/lambda-align'
   dh_auto_build
	make -j1
make[1]: Entering directory '/vagrant/lambda-align/obj-x86_64-linux-gnu'
/usr/bin/cmake -H/vagrant/lambda-align -B/vagrant/lambda-align/obj-x86_64-linux-gnu --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /vagrant/lambda-align/obj-x86_64-linux-gnu/CMakeFiles /vagrant/lambda-align/obj-x86_64-linux-gnu/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[2]: Entering directory '/vagrant/lambda-align/obj-x86_64-linux-gnu'
make -f src/CMakeFiles/lambda.dir/build.make src/CMakeFiles/lambda.dir/depend
make[3]: Entering directory '/vagrant/lambda-align/obj-x86_64-linux-gnu'
cd /vagrant/lambda-align/obj-x86_64-linux-gnu && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /vagrant/lambda-align /vagrant/lambda-align/src /vagrant/lambda-align/obj-x86_64-linux-gnu /vagrant/lambda-align/obj-x86_64-linux-gnu/src /vagrant/lambda-align/obj-x86_64-linux-gnu/src/CMakeFiles/lambda.dir/DependInfo.cmake --color=
Scanning dependencies of target lambda
make[3]: Leaving directory '/vagrant/lambda-align/obj-x86_64-linux-gnu'
make -f src/CMakeFiles/lambda.dir/build.make src/CMakeFiles/lambda.dir/build
make[3]: Entering directory '/vagrant/lambda-align/obj-x86_64-linux-gnu'
[ 25%] Building CXX object src/CMakeFiles/lambda.dir/lambda.cpp.o
cd /vagrant/lambda-align/obj-x86_64-linux-gnu/src && /usr/bin/c++   -DCMAKE_BUILD_TYPE=\"None\" -DLAMBDA_MMAPPED_DB=1 -DSEQAN_APP_VERSION=\"1.9.0\" -DSEQAN_DATE=\"\" -DSEQAN_HAS_BZIP2=1 -DSEQAN_HAS_EXECINFO=1 -DSEQAN_HAS_OPENMP="1 -DSEQAN_GLOBAL_EXCEPTION_HANDLER" -DSEQAN_HAS_ZLIB=1 -DSEQAN_REVISION=\"\" -DSEQAN_VERSION_STRING=\"2.2.0\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE  -g -O2 -fdebug-prefix-map=/vagrant/lambda-align=. -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2   -fopenmp -Wno-vla -flto=3   -o CMakeFiles/lambda.dir/lambda.cpp.o -c /vagrant/lambda-align/src/lambda.cpp
In file included from /vagrant/lambda-align/src/lambda.cpp:35:0:
/vagrant/lambda-align/src/options.hpp:351:21: warning: macro "__DATE__" might prevent reproducible builds [-Wdate-time]
     setDate(parser, __DATE__);
                     ^~~~~~~~
In file included from /vagrant/lambda-align/src/lambda.cpp:37:0:
/vagrant/lambda-align/src/lambda.hpp: In function ‘int iterateMatchesFullSimd(TLocalHolder&)’:
/vagrant/lambda-align/src/lambda.hpp:1963:22: error: expected nested-name-specifier before ‘SimdVector’
     typedef typename SimdVector<int16_t>::Type                          TSimdAlign;
                      ^~~~~~~~~~
/vagrant/lambda-align/src/lambda.hpp:1963:32: error: expected initializer before ‘<’ token
     typedef typename SimdVector<int16_t>::Type                          TSimdAlign;
                                ^
/vagrant/lambda-align/src/lambda.hpp:1966:39: error: ‘TSimdAlign’ was not declared in this scope
     unsigned const sizeBatch = LENGTH<TSimdAlign>::VALUE;
                                       ^~~~~~~~~~
/vagrant/lambda-align/src/lambda.hpp:1966:49: error: template argument 1 is invalid
     unsigned const sizeBatch = LENGTH<TSimdAlign>::VALUE;
                                                 ^
/vagrant/lambda-align/src/lambda.hpp:1973:11: error: the value of ‘TSimdAlign’ is not usable in a constant expression
     Score<TSimdAlign, ScoreSimdWrapper<typename TGlobalHolder::TScoreScheme> > simdScoringScheme(seqanScheme(context(lH.gH.outfile).scoringScheme));
           ^~~~~~~~~~
/vagrant/lambda-align/src/lambda.hpp:1966:39: note: ‘TSimdAlign’ was not declared ‘constexpr’
     unsigned const sizeBatch = LENGTH<TSimdAlign>::VALUE;
                                       ^~~~~~~~~~
/vagrant/lambda-align/src/lambda.hpp:1973:23: error: ‘ScoreSimdWrapper’ was not declared in this scope
     Score<TSimdAlign, ScoreSimdWrapper<typename TGlobalHolder::TScoreScheme> > simdScoringScheme(seqanScheme(context(lH.gH.outfile).scoringScheme));
                       ^~~~~~~~~~~~~~~~
/vagrant/lambda-align/src/lambda.hpp:1973:76: error: type/value mismatch at argument 1 in template parameter list for ‘template<class TValue, class TSpec> class seqan::Score’
     Score<TSimdAlign, ScoreSimdWrapper<typename TGlobalHolder::TScoreScheme> > simdScoringScheme(seqanScheme(context(lH.gH.outfile).scoringScheme));
```

Did I miss anything?

**Comment by h-2** [comment]
Dear Sascha,
thanks for working on the lambda package first of all! The recommended stable version of lambda is 1.0.0 and this works with SeqAn-2.2.0, as well. The development version of lambda (on which the 1.9.0 release is based) tracks a more recent  snapshot of SeqAn so it won't work with 2.2.0.

But I really would recommend the 1.0.0 for packaging right now even if that weren't the case, because I expect major changes and incompatibilities *within* the 1.9.* cycle. The 2.0.0 will be stable again and ready for packaging.

**Comment by satta** [comment]
OK, understood. 1.0.0 builds fine indeed with SeqAn 2.2.0. Thanks for the quick reply!
